export const MOCK_STATS = {
  totalScans: 1284, googleReviews: 347, averageRating: 4.7,
  positiveReviews: 312, negativeFeedback: 35, conversionRate: 27,
  scansThisWeek: 94, reviewsThisMonth: 48,
};

export const MOCK_REVIEWS = [
  {
    id: '1',
    customer: 'FOOD SPA CAFE & SALON',
    avatar: 'FS',
    rating: 5,
    preview: 'Excellent food, relaxing atmosphere, and very friendly staff. Highly recommended!',
  
    status: 'ACTIVE',
    platform: 'google',
  },
  {
    id: '2',
    customer: 'ROSETTE COUTURE',
    avatar: 'RC',
    rating: 5,
    preview: 'Beautiful collection with premium quality fabrics. Loved the customer service!',
    
    status: 'ACTIVE',
    platform: 'google',
  },
  {
    id: '3',
    customer: 'SCARED MIND',
    avatar: 'SM',
    rating: 4,
    preview: 'Very peaceful environment with professional guidance. A wonderful experience.',
    
    status: 'ACTIVE',
    platform: 'google',
  },
  {
    id: '4',
    customer: 'SHINE HERBS SALON',
    avatar: 'SH',
    rating: 5,
    preview: 'The haircut and facial were amazing. Staff was polite and the salon was very clean.',
    
    status: 'ACTIVE',
    platform: 'google',
  },
  {
    id: '5',
    customer: 'RAJDEEP COLLECTION',
    avatar: 'RC',
    rating: 4,
    preview: 'Great variety of clothing at reasonable prices. Will definitely shop again.',

    status: 'ACTIVE',
    platform: 'google',
  },
  {
    id: '6',
    customer: 'MY SHOPPEE',
    avatar: 'MS',
    rating: 5,
    preview: 'Everything I needed was available. Fast billing and excellent customer service.',
    
    status: 'ACTIVE',
    platform: 'google',
  },
  {
    id: '7',
    customer: 'THE GULATIS',
    avatar: 'TG',
    rating: 5,
    preview: 'Delicious food with outstanding hospitality. One of the best dining experiences.',
    
    status: 'ACTIVE',
    platform: 'google',
  },
  {
    id: '8',
    customer: 'AIRA BY TARUNI',
    avatar: 'AT',
    rating: 4,
    preview: 'Elegant ethnic wear and excellent fitting. Highly satisfied with my purchase.',
    
    status: 'ACTIVE',
    platform: 'google',
  },
  {
    id: '9',
    customer: 'PRIME SPORTS',
    avatar: 'PS',
    rating: 5,
    preview: 'Wide range of sports equipment with genuine products and helpful staff.',
    
    status: 'ACTIVE',
    platform: 'google',
  },
  {
    id: '10',
    customer: 'SO DELHI KHARI BAOLI',
    avatar: 'SD',
    rating: 5,
    preview: 'Authentic flavors, fresh ingredients, and quick service. A must-visit place!',
    
    status: 'ACTIVE',
    platform: 'google',
  },
];
export const MOCK_FEEDBACK = [
  {
    id: '1',
    customer: 'FOOT SPA CAFE & SALON',
    rating: 2,
    message: 'The QR stand was not clearly visible near the billing counter. Customers had difficulty finding it to leave reviews.',
    date: '4DAYS AGO',
    status: 'unresolved',
  },
  {
    id: '2',
    customer: 'ROSETTE COUTURE',
    rating: 1,
    message: 'The review page took too long to load after scanning the QR code. Please improve the loading speed.',
    date: '5 DAYS AGO',
    status: 'resolved',
  },
  {
    id: '3',
    customer: 'SCARED MIND',
    rating: 2,
    message: 'The QR code was damaged and could not be scanned from several mobile devices.',
    date: '11 JUNE',
    status: 'unresolved',
  },
  {
    id: '4',
    customer: 'SHINE HERBS SALON',
    rating: 3,
    message: 'Everything worked well, but it would be helpful if customers received a thank-you message after submitting a review.',
    date: '5 DAYS AGO',
    status: 'resolved',
  },
  {
    id: '5',
    customer: 'RAJDEEP COLLECTION',
    rating: 2,
    message: 'SAMPLE FEEDBACK.',
    date: '26 JUNE',
    status: 'resolved',
  },
  {
    id: '6',
    customer: 'MY SHOPPEE',
    rating: 2,
    message: 'The QR code sticker has faded over time and needs to be replaced for better scanning.',
    date: '2 JUNE ',
    status: 'resolved',
  },
  {
    id: '7',
    customer: 'THE GULATIS',
    rating: 1,
    message: 'Review submissions occasionally fail due to poor internet connectivity at the store.',
    date: '12 JUNE',
    status: 'unresolved',
  },
  {
    id: '8',
    customer: 'AIRA BY TARUNI',
    rating: 3,
    message: 'Customers suggested adding social media links alongside the review page for easier engagement.',
    date: '6 DAYS AGO',
    status: 'resolved',
  },
  {
    id: '9',
    customer: 'PRIME SPORTS',
    rating: 2,
    message: 'The review page looks slightly misaligned on tablets. A responsive layout would improve the experience.',
    date: '3 JULY',
    status: 'unresolved',
  },
  {
    id: '10',
    customer: 'SO DELHI KHARI BAOLI',
    rating: 2,
    message: 'The review QR was placed too far from the checkout counter. Moving it closer may increase customer participation.',
    date: '19 JUNE',
    status: 'resolved',
  },
];

export const MOCK_CUSTOMERS = [
  {
    id: '1',
    name: 'FOOD SPA CAFE & SALON',
    email: 'foodspa@gmail.com',
    visits: 18,
    avgRating: 4.9,
    lastVisit: '10 JUNE',
    totalSpend: '₹18,500',
  },
  {
    id: '2',
    name: 'ROSETTE COUTURE',
    email: 'prettysidhu84@gmail.com',
    visits: 14,
    avgRating: 4.8,
    lastVisit: '27 JUNE',
    totalSpend: '₹42,300',
  },
  {
    id: '3',
    name: 'SCARED MIND',
    email: 'kunwaroberoi21@gmail.com',
    visits: 11,
    avgRating: 4.7,
    lastVisit: '11 JUNE',
    totalSpend: '₹12,800',
  },
  {
    id: '4',
    name: 'SHINE HERBS SALON',
    email: 'birinderhr@gmail.com',
    visits: 16,
    avgRating: 4.9,
    lastVisit: '27 JUNE',
    totalSpend: '₹26,700',
  },
  {
    id: '5',
    name: 'RAJDEEP COLLECTION',
    email: 'rajbansal@gmail.com',
    visits: 13,
    avgRating: 4.8,
    lastVisit: '26 JUNE',
    totalSpend: '₹35,900',
  },
  {
    id: '6',
    name: 'MY SHOPPEE',
    email: 'sanjeevmyshoppee@gmail.com',
    visits: 10,
    avgRating: 4.5,
    lastVisit: '26 JUNE',
    totalSpend: '₹9,600',
  },
  {
    id: '7',
    name: 'THE GULATIS',
    email: 'thegulatis@gmail.com',
    visits: 20,
    avgRating: 5.0,
    lastVisit: '19 JUNE',
    totalSpend: '₹48,000',
  },
  {
    id: '8',
    name: 'AIRA BY TARUNI',
    email: 'aira.bytaruni@gmail.com',
    visits: 9,
    avgRating: 4.6,
    lastVisit: '27 JUNE',
    totalSpend: '₹29,400',
  },
  {
    id: '9',
    name: 'PRIME SPORTS',
    email: 'primesports@gmail.com',
    visits: 12,
    avgRating: 4.8,
    lastVisit: '23 JUNE',
    totalSpend: '₹38,700',
  },
  {
    id: '10',
    name: 'SO DELHI KHARI BAOLI',
    email: 'anuj6504@gmail.com',
    visits: 15,
    avgRating: 4.9,
    lastVisit: '20 JUNE',
    totalSpend: '₹42,000',
  }

  ]
export const MOCK_WEEKLY_SCANS = [42, 58, 35, 70, 89, 65, 94];
export const MOCK_MONTHLY_REVIEWS = [12, 18, 22, 15, 28, 35, 42, 38, 45, 52, 48, 55];

export const MOCK_QR_CODES = [
  { id:'1', name:'Main Entrance', scans:524, link:'https://upranko.com/r/cafe-main', created:'2024-05-01', status:'active' },
  { id:'2', name:'Table QR — Zone A', scans:312, link:'https://upranko.com/r/cafe-table-a', created:'2024-05-10', status:'active' },
  { id:'3', name:'Counter QR', scans:448, link:'https://upranko.com/r/cafe-counter', created:'2024-05-15', status:'active' },
];
